services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: cmd/app/Dockerfile
    container_name: smartnotes-backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - JWT_SECRET=supersecret
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./smartnotes-frontend
      dockerfile: Dockerfile
    container_name: smartnotes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: